Use apps/v1 type for StatefulSetSpec in RabbitmqCluster override
rabbitmq/cluster-operator pull request #1170
Opened 2022-10-26 09:06 UTC by DanielePalaia

This closes #

https://app.zenhub.com/workspaces/service-operator-experience-623895d9b17eb7001156689f/issues/rabbitmq/cluster-operator/1152

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed

## Summary Of Changes

We are now using apps/v1 StatefulSetSpec type in the override section of  RabbitmqClusterOverrideSpec instead of defining our own StatefulSetSpec type.

There is now a fix for controller-gen that allow us to correctly manage EmbeddedObjectMeta objects
https://github.com/kubernetes-sigs/controller-tools/pull/557 putting the option generateEmbeddedObjectMeta=true to controller-gen

## Additional Context

https://app.zenhub.com/workspaces/service-operator-experience-623895d9b17eb7001156689f/issues/rabbitmq/cluster-operator/1152

https://github.com/rabbitmq/cluster-operator/pull/175

https://github.com/kubernetes-sigs/controller-tools/pull/557

## Local Testing

Please ensure you run the unit, integration and system tests before approving the PR.

To run the unit and integration tests:

```
$ make unit-tests integration-tests
```

You will need to target a k8s cluster and have the operator deployed for running the system tests.

For example, for a Kubernetes context named `dev-bunny`:
```
$ kubectx dev-bunny
$ make destroy deploy-dev
# wait for operator to be deployed
$ make system-tests
```

2022-10-26 09:33 UTC, MirahImage approved these changes

2022-10-26 14:20 UTC, coro requested changes
I found this caused failures upon upgrade with one of our documented examples:
```
error: error validating "docs/examples/default-security-context/rabbitmq.yaml": error validating data: [ValidationError(RabbitmqCluster.spec.override.statefulSet.spec): missing required field "selector" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.override.statefulSet.spec, ValidationError(RabbitmqCluster.spec.override.statefulSet.spec): missing required field "serviceName" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.override.statefulSet.spec]; if you choose to ignore these errors, turn validation off with --validate=false
```

This is using the following manifest:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: default-security-context
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            securityContext: {}
            containers: []
            initContainers:
            - name: setup-container
              securityContext: {}
```

I also saw this on upgrade with the 'multiple-disks' example:
```
1.6667935497354186e+09	ERROR	Reconciler error	{"controller": "rabbitmqcluster", "controllerGroup": "rabbitmq.com", "controllerKind": "RabbitmqCluster", "RabbitmqCluster": {"name":"multiple-disks","namespace":"default"}, "namespace": "default", "name": "multiple-disks", "reconcileID": "57c342bb-decf-4fde-a3e7-c42aebcb6456", "error": "RabbitmqCluster.rabbitmq.com \"multiple-disks\" is invalid: spec.override.statefulSet.spec.selector: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
```

Is there a way to avoid these validations on embedded types?

2022-10-27 09:33 UTC, MirahImage commented
Right, but given they're now required, whereas they seemingly weren't necessary before, it seems that we need to make a webhook to populate those fields as necessary

2022-11-02 08:30 UTC, DanielePalaia commented
Close this one as it will be replaced by another one to just implement the Minimum Ready Seconds functionality

2022-11-02 08:30 UTC, closed without merging