Make edits for s390x support
rabbitmq/cluster-operator pull request #1399
Opened 2023-07-13 20:26 UTC by Joshua-Beha

This closes #1396 

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed

## Summary Of Changes
Use docker buildx to create a multi-arch manifest that includes support for amd64 and s390x architectures.

## Additional Context
NA

## Local Testing
Works as expected on both s390x Kubernetes cluster and x86 Kubernetes cluster.

Please ensure you run the unit, integration and system tests before approving the PR.

To run the unit and integration tests:

```
$ make unit-tests integration-tests
```

You will need to target a k8s cluster and have the operator deployed for running the system tests.

For example, for a Kubernetes context named `dev-bunny`:
```
$ kubectx dev-bunny
$ make destroy deploy-dev
# wait for operator to be deployed
$ make system-tests
```

2023-07-17 12:22 UTC, Zerpet requested changes
The change is valid. Attempting to build for s390x arch before this PR resulted in an error:

<details>
<summary>error output</summary>

```
 => ERROR [etc-builder 2/3] RUN echo "rabbitmq-cluster-operator:x:1000:" > /etc/group &&     echo "rabbitmq-cluster-operator:x:1000:1000::/home/rabbitm  0.3s
------
 > [etc-builder 2/3] RUN echo "rabbitmq-cluster-operator:x:1000:" > /etc/group &&     echo "rabbitmq-cluster-operator:x:1000:1000::/home/rabbitmq-cluster-operator:/usr/sbin/nologin" > /etc/passwd:
0.324 exec /bin/sh: exec format error
------
Dockerfile:28
--------------------
  27 |
  28 | >>> RUN echo "rabbitmq-cluster-operator:x:1000:" > /etc/group && \
  29 | >>>     echo "rabbitmq-cluster-operator:x:1000:1000::/home/rabbitmq-cluster-operator:/usr/sbin/nologin" > /etc/passwd
  30 |
--------------------
ERROR: failed to solve: process "/bin/sh -c echo \"rabbitmq-cluster-operator:x:1000:\" > /etc/group &&     echo \"rabbitmq-cluster-operator:x:1000:1000::/home/rabbitmq-cluster-operator:/usr/sbin/nologin\" > /etc/passwd" did not complete successfully: exit code: 1
```

Notice `exec /bin/sh: exec format error`
</details>

After this PR, this builds successfully. The changes to the Dockerfile are the ground work to make it possible to build in linux s390x, however, this won't suffice to start producing images in that architecture. That will require changes to our CI, which may not be trivial.

There's also a change request to the `Makefile` to not build by default on `s390x` architecture.

2023-07-17 12:22 UTC, Zerpet commented on Makefile
> +PLATFORMS ?= linux/amd64,linux/s390x
I don't think we want to build on `linux/s390x` every time. I would change this to default to `linux/amd64`, or even to the current architecture from the `uname` output.

2023-08-07 05:31 UTC, Sapana-Khemkar commented
@Joshua-Beha look at PR https://github.com/rabbitmq/cluster-operator/pull/1421, you have to do similar changes in CI workflow for s390.

2023-08-08 18:49 UTC, Joshua-Beha commented
Updated to add s390x architecture image to the automation and remove s390x from being build by default from the Makefile

2023-08-09 09:22 UTC, Zerpet commented
The changes look good. There are conflicts with the `main` branch, kinda expected since #1421 changed the same file of this PR. Can you rebase your branch on top of main?

2023-08-09 11:47 UTC, Joshua-Beha commented
Should be rebased now

2023-08-09 15:31 UTC, Sapana-Khemkar commented
@Joshua-Beha just do changes in build-test-publish.yml. Revert all other changes as they are not required

2023-08-10 14:36 UTC, Zerpet approved these changes

2023-08-10 14:37 UTC, merged

2023-08-10 14:37 UTC, Zerpet commented
Thank you!