Guidelines for non-strict semver (#265)
rabbitmq/cluster-operator pull request #281
Opened 2020-08-26 14:55 UTC by harshac

This closes #265

**Note to reviewers:** remember to look at the commits in this PR and consider if they can be squashed

## Summary Of Changes

## Additional Context

## Local Testing

Please ensure you run the unit, integration and system tests before approving the PR.

To run the unit and integration tests:

```
$ make unit-tests integration-tests
```

You will need to target a k8s cluster and have the operator deployed for running the system tests.

For example, for a Kubernetes context named `dev-bunny`:
```
$ kubectx dev-bunny
$ make destroy deploy-dev
# wait for operator to be deployed
$ make system-tests
```

2020-08-26 15:00 UTC, MirahImage reviewed
The use of RFC 2119 feels a bit like overkill, given that we're not following strict semver, so the version is more guidance rather than a strict statement. While we will attempt to generally follow semver, we cannot guarantee that we will not ship what ends up being a breaking change in a minor or patch release.

2020-08-27 08:15 UTC, ChunyiLyu approved these changes
LGTM

2020-08-27 08:51 UTC, harshac commented
> The use of RFC 2119 feels a bit like overkill, given that we're not following strict semver, so the version is more guidance rather than a strict statement. While we will attempt to generally follow semver, we cannot guarantee that we will not ship what ends up being a breaking change in a minor or patch release.

I agree that we are not following strict semver. However, the guidelines here can be more or less followed. I think use of RFC 2119 is ok unless it's otherwise not conveying the intent.

2020-08-27 08:55 UTC, MirahImage approved these changes

2020-08-27 09:11 UTC, merged

2020-08-27 09:16 UTC, ferozjilla requested changes

2020-08-27 09:16 UTC, ferozjilla commented on README.md
> +[Here](version_guidelines.md) are some guidelines on how we implement non-strict semver. The version number MAY or MAY NOT follow the semver rules. Hence, we highly recommend to read
```suggestion
[The versioning guidelines document](version_guidelines.md) contains some guidelines on how we implement non-strict semver. The version number MAY or MAY NOT follow the semver rules. Hence, we highly recommend to read
```

2020-08-27 09:16 UTC, ferozjilla commented on README.md
> +RabbitMQ Cluster Kubernetes Operator follows non-strict [semver. More details about other versioning strategies that were considered can be found
```suggestion
RabbitMQ Cluster Kubernetes Operator follows non-strict [semver](https://semver.org/). More details about other versioning strategies that were considered can be found
```

2020-08-27 09:16 UTC, ansd requested changes

2020-08-27 09:16 UTC, ansd commented on README.md
> +[here](https://github.com/rabbitmq/cluster-operator/blob/main/docs/proposals/20200806-versioning-release-strategy.md).
I would delete the second sentence since it's already mentioned in version_guidelines.md and is not that relevant for the main README.

2020-08-27 11:23 UTC, harshac commented on version_guidelines.md
> +4. Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes and/or CVE fixes are introduced.
I think the MUST here is correct. I do not see a scenario where we will have a bug fix but not increment the patch version, unless it's being released in a minor or a major which is covered in those sections. Am I missing something?