kubectl rabbitmq perf test improvements
rabbitmq/cluster-operator pull request #921
Opened 2021-12-14 14:38 UTC by MirahImage

## Summary Of Changes
Deploys perf-test and stream-perf-test as Kubernetes Jobs, rather than running pods directly.

## Additional Context
This is designed to make clean-up easier.

2021-12-16 15:12 UTC, mkuratczyk commented
For me, the plugin stopped working with these changes:

```
$ kubectl rabbitmq create foo
error: Unexpected args: []
See 'kubectl apply -h' for help and examples

# after deploying an instance with a version from main
$ kubectl rabbitmq perf-test foo
error: the server doesn't have a resource type ""
```

2022-01-03 16:30 UTC, Zerpet approved these changes
Works for me :shipit:

2022-01-11 12:17 UTC, coro commented
A couple questions from me:

What's the expected method of sourcing prometheus metrics from perf test in this case? Previously there was a service created - do you get the same output from scraping the pods directly?

Can we also hide the output from the `pushd`/`popd` as well?
New output:
```
$ ./bin/kubectl-rabbitmq perf-test billing --rate 100
/var/folders/gm/mgfz1ccs4t7_tbh12qfkprxm0000gp/T/tmp.11LqVZJN ~/GolandProjects/cluster-operator
job.batch/perf-test created
~/GolandProjects/cluster-operator
```
compared with old:
```
$ k rabbitmq perf-test billing --rate 100
service/perf-test created
pod/perf-test created
```

The perf-test command works fine, but the stream one doesn't out of the box. I've checked on different versions of RMQ - it seems the one on main doesn't hit this issue, but this branch does:

```
k logs stream-perf-test-zpwfd
java.lang.IllegalArgumentException: Wrong scheme in rabbitmq-stream URI: stream. Should be rabbitmq-stream or rabbitmq-stream+tls
	at com.rabbitmq.stream.impl.StreamEnvironmentBuilder.toUri(StreamEnvironmentBuilder.java:74)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.rabbitmq.stream.impl.StreamEnvironmentBuilder.uris(StreamEnvironmentBuilder.java:98)
	at com.rabbitmq.stream.impl.StreamEnvironmentBuilder.uris(StreamEnvironmentBuilder.java:44)
	at com.rabbitmq.stream.perf.StreamPerfTest.call(StreamPerfTest.java:546)
	at com.rabbitmq.stream.perf.StreamPerfTest.call(StreamPerfTest.java:86)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.executeHelpRequest(CommandLine.java:1929)
	at picocli.CommandLine.executeHelpRequest(CommandLine.java:1909)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2176)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.rabbitmq.stream.perf.StreamPerfTest.run(StreamPerfTest.java:382)
	at com.rabbitmq.stream.perf.StreamPerfTest.main(StreamPerfTest.java:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```
using cluster-operator 1.10.0, example rmq:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: billing
spec:
  replicas: 3
  image: rabbitmq:3.9-management
  rabbitmq:
    additionalPlugins:
    - rabbitmq_stream
```
Otherwise works well for me, and I like the change, thanks!

2022-01-11 13:21 UTC, MirahImage commented
> What's the expected method of sourcing prometheus metrics from perf test in this case? Previously there was a service created - do you get the same output from scraping the pods directly?

It actually didn't create a service before either, it just documented that it was possible to create a service. It is still possible to create a service, the same pod selectors as recommended before are still valid and continue to be documented.

2022-01-11 14:27 UTC, MirahImage commented
>What's the expected method of sourcing prometheus metrics from perf test in this case? Previously there was a service created - do you get the same output from scraping the pods directly?

Unfortunately, creating a service would defeat the purpose of using a Job, namely, allowing the perf-test command to clean up after itself. Thankfully, it's possible to monitor the job using a podMonitor instead of a serviceMonitor, so I have updated the instructions with the relevant podMonitor.

2022-01-13 12:03 UTC, coro requested changes
Sorry to be a pain; the stream perf test command now works but the pushd/popd output is still shown, and the echo statements are now also shown:
```
$ ./bin/kubectl-rabbitmq perf-test billing --rate 100
/var/folders/gm/mgfz1ccs4t7_tbh12qfkprxm0000gp/T/tmp.lzJyhNZe ~/GolandProjects/cluster-operator
+ echo 'apiVersion: batch/v1'
+ echo 'kind: Job'
+ echo metadata:
+ echo '  name: perf-test'
+ echo '  labels:'
...
```

2022-01-13 13:13 UTC, MirahImage commented
I've removed the output, at the consequence of more technically incorrect bash. Unfortunately, it seems that due to the nature of kubectl plugins, it's not possible to hide `pushd`/`popd` output, so we're forced to use `cd`, which should generally be avoided in scripts.

2022-01-13 13:54 UTC, merged